#!/usr/bin/env python3
# Translating the chinese manual

import sys

from PIL import Image
import pytesseract
from googletrans import Translator


if len(sys.argv > 0):
    image_path = str(sys.argv[0])
else:
    printf("cant really do anyrhing without the original manual.\n
            Try to fiond it and make a good picture.. ;)")
    os.exit(1)
image = Image.open(image_path)
image_text = pytesseract.load_image(image)
trans = Translator()
translated  = str(trans.translate(image_text, dest="german").text)


